const UserActionTypes ={
    SET_CURRENT_USER:"SET_CURRENT_USER",
    GOOGLE_SIGN_IN_START : "GOOGLE_SIGN_IN_START",
    EMAIL_SIGN_IN_START : "EMAIL_SIGN_IN_START",
    SIGN_IN_SUCCESS : "SIGN_IN_SUCCESS",
    SIGN_IN_FAIL : "SIGN_IN_FAIL",
    CHECK_USER_SESSION : "CHECK_USER_SESSION",
    SIGNOUT_START :"SIGNOUT_START",
    SIGNOUT_SUCCESS :"SIGNOUT_SUCCESS",
    SIGNOUT_FAIL : "SIGNOUT_FAIL",
    SIGNUP_START : "SIGNUP_START",
    SIGNUP_SUCCESS : "SIGNUP_SUCCESS",
    SIGNUP_FAIL : "SIGNUP_FAIL"

}

export default UserActionTypes;